import json
import os

notebook_path = "research_implimentation.ipynb"

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cell_3_source = [
    "# ============================================================\n",
    "# CELL 3: SUMO INFRASTRUCTURE GENERATION\n",
    "# ============================================================\n",
    "import os, subprocess, sys\n",
    "\n",
    "SUMO_DIR = '/content/cotop-implementation/sumo_config'\n",
    "os.makedirs(SUMO_DIR, exist_ok=True)\n",
    "\n",
    "NET_FILE   = f'{SUMO_DIR}/hangzhou.net.xml'\n",
    "TRIPS_FILE = f'{SUMO_DIR}/trips.trips.xml'\n",
    "ROU_FILE   = f'{SUMO_DIR}/hangzhou.rou.xml'\n",
    "CFG_FILE   = f'{SUMO_DIR}/hangzhou.sumocfg'\n",
    "\n",
    "# ── Locate SUMO binaries (Colab puts them in non-standard paths) ──────────\n",
    "def find_sumo_bin(name):\n",
    "    \"\"\"Search common SUMO install locations and return the full path.\"\"\"\n",
    "    candidates = [\n",
    "        f'/usr/bin/{name}',\n",
    "        f'/usr/local/bin/{name}',\n",
    "        f'/usr/share/sumo/bin/{name}',\n",
    "        f'/opt/sumo/bin/{name}',\n",
    "    ]\n",
    "    try:\n",
    "        result = subprocess.run(['which', name], capture_output=True, text=True)\n",
    "        if result.returncode == 0:\n",
    "            return result.stdout.strip()\n",
    "    except Exception:\n",
    "        pass\n",
    "    for c in candidates:\n",
    "        if os.path.isfile(c):\n",
    "            return c\n",
    "    return None\n",
    "\n",
    "# Add SUMO bin dirs to PATH so all sumo tools are discoverable\n",
    "for sumo_bin_dir in ['/usr/bin', '/usr/local/bin', '/usr/share/sumo/bin']:\n",
    "    if sumo_bin_dir not in os.environ.get('PATH', ''):\n",
    "        os.environ['PATH'] = sumo_bin_dir + ':' + os.environ.get('PATH', '')\n",
    "\n",
    "NETGEN = find_sumo_bin('netgenerate')\n",
    "if NETGEN is None:\n",
    "    r = subprocess.run(['find', '/usr', '-name', 'netgenerate', '-type', 'f'], capture_output=True, text=True)\n",
    "    hits = r.stdout.strip().splitlines()\n",
    "    NETGEN = hits[0] if hits else None\n",
    "\n",
    "if NETGEN is None:\n",
    "    raise RuntimeError('netgenerate not found. Re-run Cell 1 to reinstall SUMO.')\n",
    "print(f'netgenerate found at: {NETGEN}')\n",
    "\n",
    "print('=' * 60)\n",
    "print('Generating 2.4 km linear road network...')\n",
    "print('=' * 60)\n",
    "\n",
    "# Step 1: Generate network — 2.4km grid (4x4 junctions × 600m = 2.4km spans)\n",
    "net_cmd = [\n",
    "    NETGEN,\n",
    "    '--grid',\n",
    "    '--grid.number', '4',\n",
    "    '--grid.length', '600',\n",
    "    '--default.lanenumber', '3',\n",
    "    '--default.speed', '13.89',\n",
    "    '--output-file', NET_FILE,\n",
    "    '--no-turnarounds', 'true',\n",
    "    '--tls.guess', 'true',\n",
    "]\n",
    "result = subprocess.run(net_cmd, capture_output=True, text=True)\n",
    "print(result.stdout[-500:] if result.stdout else '(no stdout)')\n",
    "if result.returncode != 0:\n",
    "    print('stderr:', result.stderr[-500:])\n",
    "\n",
    "if os.path.exists(NET_FILE):\n",
    "    print(f'✅ Network generated: {NET_FILE}')\n",
    "else:\n",
    "    raise RuntimeError('❌ Network generation failed. See stderr above.')\n",
    "\n",
    "print()\\nprint('Generating dense vehicle traffic (period=0.2s)...')\n",
    "\n",
    "# Step 2: Locate randomTrips.py\n",
    "SUMO_HOME = os.environ.get('SUMO_HOME', '/usr/share/sumo')\n",
    "RANDOM_TRIPS = f'{SUMO_HOME}/tools/randomTrips.py'\n",
    "if not os.path.exists(RANDOM_TRIPS):\n",
    "    r2 = subprocess.run(['find', '/usr', '-name', 'randomTrips.py'], capture_output=True, text=True)\n",
    "    hits2 = r2.stdout.strip().splitlines()\n",
    "    RANDOM_TRIPS = hits2[0] if hits2 else RANDOM_TRIPS\n",
    "print(f'randomTrips.py at: {RANDOM_TRIPS}')\n",
    "\n",
    "trip_cmd = [\n",
    "    sys.executable, RANDOM_TRIPS,\n",
    "    '-n', NET_FILE,\n",
    "    '-o', TRIPS_FILE,\n",
    "    '-r', ROU_FILE,\n",
    "    '--period', '0.2',\n",
    "    '--begin', '0',\n",
    "    '--end', '1000',\n",
    "    '--validate',\n",
    "]\n",
    "result2 = subprocess.run(trip_cmd, capture_output=True, text=True)\n",
    "print(result2.stdout[-500:] if result2.stdout else '(no stdout)')\n",
    "if result2.returncode != 0:\n",
    "    print('stderr:', result2.stderr[-300:])\n",
    "\n",
    "if os.path.exists(ROU_FILE):\n",
    "    print(f'✅ Route file generated: {ROU_FILE}')\n",
    "else:\n",
    "    raise RuntimeError('❌ Route generation failed. See stderr above.')\n",
    "\n",
    "print()\\nprint('Creating SUMO configuration file...')\n",
    "\n",
    "# Step 3: Write .sumocfg\n",
    "sumocfg_content = '''<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
    "<configuration xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n",
    "               xsi:noNamespaceSchemaLocation=\"http://sumo.dlr.de/xsd/sumoConfiguration.xsd\">\n",
    "    <input>\n",
    "        <net-file value=\"hangzhou.net.xml\"/>\n",
    "        <route-files value=\"hangzhou.rou.xml\"/>\n",
    "    </input>\n",
    "    <time>\n",
    "        <begin value=\"0\"/>\n",
    "        <end value=\"1000\"/>\n",
    "        <step-length value=\"0.1\"/>\n",
    "    </time>\n",
    "    <processing>\n",
    "        <ignore-route-errors value=\"true\"/>\n",
    "        <collision.action value=\"warn\"/>\n",
    "    </processing>\n",
    "    <report>\n",
    "        <verbose value=\"false\"/>\n",
    "        <no-step-log value=\"true\"/>\n",
    "        <no-warnings value=\"true\"/>\n",
    "    </report>\n",
    "</configuration>\n",
    "'''\n",
    "\n",
    "with open(CFG_FILE, 'w') as f:\n",
    "    f.write(sumocfg_content)\n",
    "print(f'✅ SUMO config written: {CFG_FILE}')\n",
    "\n",
    "# Step 4: Quick validation\n",
    "SUMO_BIN = find_sumo_bin('sumo')\n",
    "if SUMO_BIN:\n",
    "    val = subprocess.run([SUMO_BIN, '-c', CFG_FILE, '--end', '1', '--no-step-log', '--no-warnings'], capture_output=True, text=True)\n",
    "    if 'Error' in val.stderr:\n",
    "        print('⚠️  SUMO validation warnings:', val.stderr[:300])\n",
    "    else:\n",
    "        print('✅ SUMO config validated successfully.')\n",
    "else:\n",
    "    print('⚠️  sumo binary not found for validation, skipping.')\n"
]

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        if len(cell['source']) > 2 and 'CELL 3: SUMO INFRASTRUCTURE GENERATION' in cell['source'][1]:
            cell['source'] = new_cell_3_source
            break

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Notebook updated!")
