import pytest
import numpy as np
import yaml
import torch

from envs.entities import Vehicle, Task, RSU, SimulationConfig
from envs.state_builder import build_state
from envs.vec_env import VECEnv

def load_default_config():
    with open("configs/paper_parameters.yaml", "r") as f:
        cfg_dict = yaml.safe_load(f)
    return SimulationConfig(**cfg_dict)

def test_state_vector_exact_dimension_and_bounds():
    config = load_default_config()
    
    # 1. Active vehicle with nominal task batch
    vehicle = Vehicle(v_id="v_test_0", pos=(1200.0, 50.0), speed=35.0, dwell_time_T_stay=15.0)
    tasks = [
        Task(task_id=i, vehicle_id="v_test_0", size_rho=3.5e6, cpu_phi=10.0e6, max_delay_d=25.0, priority=0.6)
        for i in range(20)
    ]
    rsus = [
        RSU(rsu_id=i, location=(i * 400.0, 0.0), cpu_capacity_f=2.0e9, queued_cpu_cycles=5.0e6, transmission_power_P_R=100.0)
        for i in range(6)
    ]
    
    s = build_state(vehicle, tasks, rsus, config)
    
    # Dimension contract: 4 (veh) + 4*20 (tasks) + 5*6 (rsus) = 114
    assert s.shape == (114,), f"State shape mismatch: expected (114,), got {s.shape}"
    assert s.dtype == np.float32, f"State dtype mismatch: expected float32, got {s.dtype}"
    
    # Normalization bounds: all features must be within [0.0, 1.0]
    assert np.all(s >= 0.0), f"Negative value detected in state: min={s.min()}"
    assert np.all(s <= 1.0), f"Unbounded value detected in state: max={s.max()}"
    assert not np.isnan(s).any(), "NaN detected in state vector"
    assert not np.isinf(s).any(), "Inf detected in state vector"

def test_state_vector_none_vehicle_padding():
    config = load_default_config()
    s_zero = build_state(None, [], [], config)
    assert s_zero.shape == (114,)
    assert np.all(s_zero == 0.0)

def test_action_space_exact_dimension_and_semantics():
    config = load_default_config()
    env = VECEnv(config=config, scenario_geometry="corridor_2400m", use_mobility_model=False)
    
    assert env.action_space.n == 7, f"Action space mismatch: expected 7 actions, got {env.action_space.n}"
    assert env.obs_dim == 114, f"Observation dimension mismatch: expected 114, got {env.obs_dim}"

def test_action_mask_feasibility_invariance():
    config = load_default_config()
    env = VECEnv(config=config, scenario_geometry="corridor_2400m", use_mobility_model=False)
    
    # Verify that valid action mask generated by environment is consistent
    # Action 0 is local standalone execution; Actions 1..6 correspond to RSUs 0..5
    for action in range(7):
        assert action in range(env.action_space.n)
